#!/bin/sh

ver=$1
input=cdb_geocoder--${ver}.sql
output=cdb_geocoder--unpackaged--${ver}.sql

echo "-- Script generated by $0 on `date`" > ${output}

# Migrate CDB functions from public schema to cdb_geocoder schema
cat ${input} |
  grep '^ *CREATE OR REPLACE FUNCTION' |
  grep -v ' cdb_geocoder\.' | # should  only match DDL hooks
  sed 's/).*$/)/' |
  sed 's/DEFAULT [^ ,)]*//g' |
  sed 's/CREATE OR REPLACE FUNCTION /ALTER FUNCTION public./' |
  sed 's/$/ SET SCHEMA cdb_geocoder;/' |
  sed 's/^/DO LANGUAGE plpgsql \$\$ BEGIN /' |
  sed "s/$/ EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'Got % (%)', SQLERRM, SQLSTATE; END; \$\$;/" |
  cat >> ${output}

# Upgrade all functions
cat ${input} | grep -v 'duplicated extension$' >> ${output}
